### ISSUE TITLE
doesn't refresh the last file found on sdcard

### ISSUE THREAD

**Issue by farvardin** [paulmach/Text-Edit-for-Android#1]
when you open and save a file from sd card from text edit, it will be loaded next time you open it, as expected. But if meanwhile you edit this file from another application (from your android phone, or from a computer connected on the phone's sd card), the data won't be refreshed from text edit's memory, displaying only the last version saved from text edit, and not the real file on the sdcard.

**Comment by paulmach** [comment]
Thanks for the comment. 

Typically a text editor will issued a message that says something like, "This file has changed, do you want to refresh it." Refreshing it automatically isn't exactly what you want because maybe you already made some good changes that would be lost.

I'll try to include this in the next release, but I can't offer a time frame for that. Alternately you could submit a patch :)

**Comment by hydrian** [comment]
I second this.  I use many program (Dropbox / Ubuntu One)  that automatically update the filesystem  I would like to know when the file has been modified outside Text Edit and ask me if I want to reload the file.  If 'no', give me a change to save the file to another filename.  Also a warning should come up when trying to save a file and it has been modified outside of Text Edit so there are no surprises.  Also I would take a look at Issue #6.  i just filed it and it sort of pertains to issues like this.

**Comment by paulmach** [comment]
This feature has been implemented and your feedback would be appreciated.

**Comment by farvardin** [comment]
Hello,

thank you, I've tested it and it seems to work well.

Regards

  Eric

----- Mail original -----
De : paulmach reply@reply.github.com
À : eforgeot@yahoo.fr
Cc : 
Envoyé le : Dimanche 4 Septembre 2011 0h47
Objet : Re: [Text-Edit-for-Android] doesn't refresh the last file found on sdcard (#1)

This feature has been implemented and your feedback would be appreciated.

##
