### ISSUE TITLE
Source for 1.4.1

### ISSUE THREAD

**Issue by CiaranG** [paulmach/Text-Edit-for-Android#4]
Hi - there doesn't appear to be any source for 1.4.1 here. Is it available elsewhere?

**Comment by paulmach** [comment]
I haven't really kept the versions separate. The current version of the source is the latest version, currently 1.4.1.  That is always the case as development is not very dynamic for this small project.

**Comment by CiaranG** [comment]
Thanks for the info (and the app!)

**Comment by CiaranG** [comment]
Are you sure the source here is right? The binary release for 1.4.1 is described as 'permission needed for new sdk', but in the source in the repo, I see the change to the new SDK, but nothing following about a permissio nchange.

**Comment by paulmach** [comment]
You are right, that was sloppy. I've added it in.
