### ISSUE TITLE
Cannot re-open file that is already open

### ISSUE THREAD

**Issue by hydrian** [paulmach/Text-Edit-for-Android#6]
Description:
Text Edit will not reopen(refresh) a file that is already open.  This is an issue if you use programs/services that update files automatically (Aka Dropbox / Ubuntu One) 

Test Case:
Open test.txt file
Alter and save text.txt with different application.
Switch back to Text Edit. 
Open the test.txt again.  (To reload changes) 
Text File show the file that is already open without the changes from the other program.  

[Work around]
Had to 'Clear Data' (loosing settings) and 'Force Stop' Text Edit to reread the file again.  

[Environment]
Text Edit 1.4.1
Motorola Droid A855
Android 2.2.2 build FRG83G

**Comment by paulmach** [comment]
Thanks for the report, I will look into this.

As a workaround, you can select, "create a new,"  DON'T save if prompted, and then reopen the first file.

**Comment by paulmach** [comment]
This feature has been implemented. Your feedback would be appreciated.
